# Generated by Django 5.0.4 on 2026-05-23 18:23

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
    ]
