# Generated by Django 5.0.4 on 2026-05-23 19:07

import django.contrib.postgres.indexes
import school.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('school', '0002_auto_20260523_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/', validators=[school.storage.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[school.storage.validate_file_size]),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'body'], name='announce_search_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'description'], name='assign_search_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=django.contrib.postgres.indexes.GinIndex(fields=['reason'], name='attendance_search_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='classroom_search_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='developmentreport',
            index=django.contrib.postgres.indexes.GinIndex(fields=['comment', 'strengths', 'areas_to_improve'], name='report_search_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=django.contrib.postgres.indexes.GinIndex(fields=['invoice_number', 'description'], name='invoice_search_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=django.contrib.postgres.indexes.GinIndex(fields=['reference', 'notes'], name='payment_search_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='student',
            index=django.contrib.postgres.indexes.GinIndex(fields=['first_name', 'last_name', 'admission_number'], name='student_search_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['first_name', 'last_name', 'email'], name='user_search_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
