# Generated by Django 5.0.4 on 2026-05-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_creditnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('teacher', 'Teacher'), ('parent', 'Parent')], default='parent', max_length=10),
        ),
    ]
