# Generated by Django 5.0.4 on 2026-06-01 10:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_add_editor_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(blank=True, help_text='Denormalised — survives user deletion.', max_length=254)),
                ('user_role', models.CharField(blank=True, help_text='Role at request time.', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('request_body', models.JSONField(blank=True, default=dict, help_text='Sanitised — no passwords/tokens.')),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_time_ms', models.PositiveIntegerField(default=0)),
                ('resource_type', models.CharField(blank=True, help_text='e.g. students, invoices', max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('action', models.CharField(choices=[('login.success', 'Login Success'), ('login.failed', 'Login Failed'), ('logout', 'Logout'), ('register', 'Register'), ('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('bulk', 'Bulk Operation'), ('action', 'Custom Action'), ('health_check', 'Health Check'), ('error', 'Server Error')], default='read', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='NULL for anonymous / unauthenticated requests.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='audit_user_ts_idx'), models.Index(fields=['resource_type', '-timestamp'], name='audit_resource_ts_idx'), models.Index(fields=['response_status', '-timestamp'], name='audit_status_ts_idx'), models.Index(fields=['action', '-timestamp'], name='audit_action_ts_idx'), models.Index(fields=['ip_address', '-timestamp'], name='audit_ip_ts_idx')],
            },
        ),
    ]
