# Generated by Django 5.0.4 on 2026-06-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='error_detail',
            field=models.TextField(blank=True, help_text="Human-readable description of what went wrong, populated for every 4xx / 5xx response. Empty for successful requests. Examples: 'email: This field is required.' | 'Only admins can delete students.' | 'Given token not valid for any token type'"),
        ),
    ]
