# Generated by Django 5.0.4 on 2026-06-19 12:09

import django.contrib.postgres.indexes
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auditlog_error_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('interested_class', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inquiries',
                'ordering': ['-created_at'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['parent_name', 'email', 'phone'], name='inquiry_search_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops'])],
            },
        ),
    ]
