# Generated by Django 5.0.4 on 2026-06-19 18:52

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_inquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date money was physically received'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Internal receipt serial, e.g. RCP-2025-001', max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='error_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='request_body',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_role',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discounted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='school.invoice')),
            ],
            options={
                'db_table': 'invoice_line_items',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date the expenditure occurred')),
                ('category', models.CharField(choices=[('salary', 'Staff Salary'), ('utilities', 'Utilities'), ('supplies', 'School Supplies'), ('maintenance', 'Maintenance & Repairs'), ('transport', 'Transport'), ('events', 'Events & Activities'), ('marketing', 'Marketing & Outreach'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='Receipt number, invoice ref, or bank reference', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditures_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expenditures',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='expenditure_date_idx'), models.Index(fields=['category'], name='expenditure_cat_idx'), django.contrib.postgres.indexes.GinIndex(fields=['description', 'reference'], name='expenditure_search_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops'])],
            },
        ),
    ]
