# Generated by Django 5.0.4 on 2026-06-21 22:01

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_payment_options_invoice_notes_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendance_search_idx',
        ),
        migrations.AddField(
            model_name='attendance',
            name='outlook',
            field=models.CharField(blank=True, help_text="Child's mood/outlook on arrival", max_length=255),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=django.contrib.postgres.indexes.GinIndex(fields=['reason', 'outlook'], name='attendance_search_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
