# Generated by Django 5.0.4 on 2026-06-22 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_remove_attendance_attendance_search_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('teacher', 'Teacher'), ('non_academic', 'Non-Academic Staff'), ('parent', 'Parent')], default='parent', max_length=20),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('marital_status', models.CharField(blank=True, max_length=20)),
                ('nationality', models.CharField(default='Nigerian', max_length=50)),
                ('state_of_origin', models.CharField(blank=True, max_length=50)),
                ('lga', models.CharField(blank=True, max_length=50)),
                ('home_address', models.TextField(blank=True)),
                ('spouse_name', models.CharField(blank=True, max_length=100)),
                ('spouse_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50)),
                ('highest_qualification', models.CharField(blank=True, max_length=100)),
                ('institution', models.CharField(blank=True, max_length=150)),
                ('year_attained', models.CharField(blank=True, max_length=4)),
                ('previous_employer', models.CharField(blank=True, max_length=150)),
                ('previous_job_title', models.CharField(blank=True, max_length=100)),
                ('teaching_philosophy', models.TextField(blank=True, help_text='Teaching approach and philosophy')),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('genotype', models.CharField(blank=True, max_length=5)),
                ('medical_conditions', models.TextField(blank=True)),
                ('shortee_1_name', models.CharField(blank=True, max_length=100)),
                ('shortee_1_phone', models.CharField(blank=True, max_length=20)),
                ('shortee_2_name', models.CharField(blank=True, max_length=100)),
                ('shortee_2_phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_profiles',
            },
        ),
    ]
