# Generated by Django 5.0.4 on 2026-06-25 23:52

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_user_role_staffprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('elementary', 'Elementary'), ('preschool', 'Preschool')], max_length=15)),
                ('attendance_present', models.PositiveSmallIntegerField(blank=True, help_text='Days the child was present this term', null=True)),
                ('attendance_total', models.PositiveSmallIntegerField(blank=True, help_text='Total school days this term', null=True)),
                ('pm_fluent_reading', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pm_elocution', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pm_handwriting', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pm_sports_games', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pm_creativity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lit_speaks_clearly', models.PositiveSmallIntegerField(blank=True, help_text='Speaks clearly and uses appropriate language', null=True)),
                ('lit_letter_sounds', models.PositiveSmallIntegerField(blank=True, help_text='Can sound and say letter sounds a–j and match to objects', null=True)),
                ('lit_phonics', models.PositiveSmallIntegerField(blank=True, help_text='Can identify and trace the sounds s, a, t, p, i, n', null=True)),
                ('lit_local_pets', models.PositiveSmallIntegerField(blank=True, help_text='Can identify and mention local pets', null=True)),
                ('lit_picture_story', models.PositiveSmallIntegerField(blank=True, help_text='Can arrange a 3-picture story in correct chronological order', null=True)),
                ('lit_comment', models.TextField(blank=True)),
                ('se_follows_routines', models.PositiveSmallIntegerField(blank=True, help_text='Follows routines, asks questions and responds to questions', null=True)),
                ('se_manages_emotions', models.PositiveSmallIntegerField(blank=True, help_text='Shows and manages emotions (anger, hunger, happiness)', null=True)),
                ('se_says_name_age', models.PositiveSmallIntegerField(blank=True, help_text='Can say name and age, follows directions and shares with others', null=True)),
                ('se_magic_words', models.PositiveSmallIntegerField(blank=True, help_text='Can say their five magic words and uses them when needed', null=True)),
                ('se_identifies_objects', models.PositiveSmallIntegerField(blank=True, help_text='Can identify and feel objects around them', null=True)),
                ('se_comment', models.TextField(blank=True)),
                ('num_count_write_20', models.PositiveSmallIntegerField(blank=True, help_text='Can count, identify, trace and write numbers 1–20', null=True)),
                ('num_shapes_colors', models.PositiveSmallIntegerField(blank=True, help_text='Can identify shapes (circle, triangle, square) and colours', null=True)),
                ('num_many_few', models.PositiveSmallIntegerField(blank=True, help_text='Can identify many/few, big/small, full/empty', null=True)),
                ('num_match_objects', models.PositiveSmallIntegerField(blank=True, help_text='Can match objects to their numbers from 1–10', null=True)),
                ('num_count_40', models.PositiveSmallIntegerField(blank=True, help_text='Can count and recite numbers 1–40', null=True)),
                ('num_comment', models.TextField(blank=True)),
                ('sci_sense_organs', models.PositiveSmallIntegerField(blank=True, help_text='Can identify the five sense organs and say what they do', null=True)),
                ('sci_plants', models.PositiveSmallIntegerField(blank=True, help_text='Can say what plants are and identify them in the environment', null=True)),
                ('sci_animals', models.PositiveSmallIntegerField(blank=True, help_text='Can identify and mention examples of animals in the locality', null=True)),
                ('sci_body_parts', models.PositiveSmallIntegerField(blank=True, help_text='Can identify different body parts and match them to what they do', null=True)),
                ('sci_weather', models.PositiveSmallIntegerField(blank=True, help_text='Can say what the weather is (rainy or sunny)', null=True)),
                ('sci_comment', models.TextField(blank=True)),
                ('pl_pencil_crayon', models.PositiveSmallIntegerField(blank=True, help_text='Can hold and use a pencil, crayon or glue stick', null=True)),
                ('pl_wash_hands', models.PositiveSmallIntegerField(blank=True, help_text='Can wash hands with minimal help', null=True)),
                ('pl_take_turns', models.PositiveSmallIntegerField(blank=True, help_text='Can take turns, follow directions and share with others', null=True)),
                ('pl_pour_liquid', models.PositiveSmallIntegerField(blank=True, help_text='Can pour liquid material with control', null=True)),
                ('pl_zip_button', models.PositiveSmallIntegerField(blank=True, help_text='Can zip a jacket, buckle shoes, wash hands properly and button shirts', null=True)),
                ('pl_table_manners', models.PositiveSmallIntegerField(blank=True, help_text='Practices good table manners and hygiene', null=True)),
                ('pl_comment', models.TextField(blank=True)),
                ('teacher_comment', models.TextField()),
                ('head_teacher_comment', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_reports', to='school.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.term')),
                ('written_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academic_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('MATH', 'Math'), ('ENGLISH', 'English'), ('SOCIAL_STUDIES', 'Social Studies'), ('SCIENCE', 'Science'), ('CRK', 'C.R.K'), ('PHSE', 'P.H.S.E'), ('CCA', 'CCA'), ('QUANT_RSN', 'Quant Reasoning'), ('VERBAL_RSN', 'Verbal Reasoning'), ('ICT', 'ICT')], max_length=20)),
                ('cat_score', models.PositiveSmallIntegerField(default=0, help_text='Continuous Assessment score')),
                ('exam_score', models.PositiveSmallIntegerField(default=0, help_text='Examination score')),
                ('wh_behaviour', models.CharField(choices=[('MS', 'Mastered Skills'), ('LS', 'Learning Skills'), ('AC', 'Area of Concern'), ('NA', 'Not Applicable')], default='LS', help_text='Comports self with good behaviour during class work', max_length=2)),
                ('wh_listens', models.CharField(choices=[('MS', 'Mastered Skills'), ('LS', 'Learning Skills'), ('AC', 'Area of Concern'), ('NA', 'Not Applicable')], default='LS', help_text='Listens attentively and gives best effort', max_length=2)),
                ('wh_completes_work', models.CharField(choices=[('MS', 'Mastered Skills'), ('LS', 'Learning Skills'), ('AC', 'Area of Concern'), ('NA', 'Not Applicable')], default='LS', help_text='Completes work on time', max_length=2)),
                ('wh_contributes', models.CharField(choices=[('MS', 'Mastered Skills'), ('LS', 'Learning Skills'), ('AC', 'Area of Concern'), ('NA', 'Not Applicable')], default='LS', help_text='Contributes to class discussions', max_length=2)),
                ('wh_homework', models.CharField(choices=[('MS', 'Mastered Skills'), ('LS', 'Learning Skills'), ('AC', 'Area of Concern'), ('NA', 'Not Applicable')], default='LS', help_text='Completes homework', max_length=2)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_scores', to='school.academicreport')),
            ],
            options={
                'db_table': 'subject_scores',
                'ordering': ['report', 'subject'],
            },
        ),
        migrations.DeleteModel(
            name='DevelopmentReport',
        ),
        migrations.AddIndex(
            model_name='academicreport',
            index=django.contrib.postgres.indexes.GinIndex(fields=['teacher_comment', 'head_teacher_comment'], name='academic_report_search_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='academicreport',
            unique_together={('student', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectscore',
            unique_together={('report', 'subject')},
        ),
    ]
